# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13model_service.proto\"%\n\x0fRequestMetaData\x12\x12\n\nrequest_id\x18\x01 \x01(\t\";\n\x10ResponseMetaData\x12\x13\n\x0bresponse_id\x18\x01 \x01(\t\x12\x12\n\nrequest_id\x18\x02 \x01(\t\"J\n\x14\x46\x61\x63\x65\x44\x65tectionRequest\x12\x1e\n\x04meta\x18\x01 \x01(\x0b\x32\x10.RequestMetaData\x12\x12\n\nface_image\x18\n \x01(\x0c\"P\n\x15\x46\x61\x63\x65\x44\x65tectionResponse\x12\x1f\n\x04meta\x18\x01 \x01(\x0b\x32\x11.ResponseMetaData\x12\x16\n\x0e\x66\x61\x63\x65_dets_json\x18\n \x01(\t\"_\n\x16\x46\x61\x63\x65RecognitionRequest\x12\x1e\n\x04meta\x18\x01 \x01(\x0b\x32\x10.RequestMetaData\x12\x12\n\nface_image\x18\n \x01(\x0c\x12\x11\n\tface_lmks\x18\x0b \x01(\x0c\"I\n\x17\x46\x61\x63\x65RecognitionResponse\x12\x1f\n\x04meta\x18\x01 \x01(\x0b\x32\x11.ResponseMetaData\x12\r\n\x05label\x18\n \x01(\t\"P\n\x1aSpeakerVerificationRequest\x12\x1e\n\x04meta\x18\x01 \x01(\x0b\x32\x10.RequestMetaData\x12\x12\n\nvoice_data\x18\n \x01(\x0c\"M\n\x1bSpeakerVerificationResponse\x12\x1f\n\x04meta\x18\x01 \x01(\x0b\x32\x11.ResponseMetaData\x12\r\n\x05label\x18\n \x01(\t2\xfe\x01\n\x0cModelService\x12\x46\n\x13\x63\x61ll_face_detection\x12\x15.FaceDetectionRequest\x1a\x16.FaceDetectionResponse\"\x00\x12L\n\x15\x63\x61ll_face_recognition\x12\x17.FaceRecognitionRequest\x1a\x18.FaceRecognitionResponse\"\x00\x12X\n\x19\x63\x61ll_speaker_verification\x12\x1b.SpeakerVerificationRequest\x1a\x1c.SpeakerVerificationResponse\"\x00\x42\x03\x80\x01\x01\x62\x06proto3')



_REQUESTMETADATA = DESCRIPTOR.message_types_by_name['RequestMetaData']
_RESPONSEMETADATA = DESCRIPTOR.message_types_by_name['ResponseMetaData']
_FACEDETECTIONREQUEST = DESCRIPTOR.message_types_by_name['FaceDetectionRequest']
_FACEDETECTIONRESPONSE = DESCRIPTOR.message_types_by_name['FaceDetectionResponse']
_FACERECOGNITIONREQUEST = DESCRIPTOR.message_types_by_name['FaceRecognitionRequest']
_FACERECOGNITIONRESPONSE = DESCRIPTOR.message_types_by_name['FaceRecognitionResponse']
_SPEAKERVERIFICATIONREQUEST = DESCRIPTOR.message_types_by_name['SpeakerVerificationRequest']
_SPEAKERVERIFICATIONRESPONSE = DESCRIPTOR.message_types_by_name['SpeakerVerificationResponse']
RequestMetaData = _reflection.GeneratedProtocolMessageType('RequestMetaData', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTMETADATA,
  '__module__' : 'model_service_pb2'
  # @@protoc_insertion_point(class_scope:RequestMetaData)
  })
_sym_db.RegisterMessage(RequestMetaData)

ResponseMetaData = _reflection.GeneratedProtocolMessageType('ResponseMetaData', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSEMETADATA,
  '__module__' : 'model_service_pb2'
  # @@protoc_insertion_point(class_scope:ResponseMetaData)
  })
_sym_db.RegisterMessage(ResponseMetaData)

FaceDetectionRequest = _reflection.GeneratedProtocolMessageType('FaceDetectionRequest', (_message.Message,), {
  'DESCRIPTOR' : _FACEDETECTIONREQUEST,
  '__module__' : 'model_service_pb2'
  # @@protoc_insertion_point(class_scope:FaceDetectionRequest)
  })
_sym_db.RegisterMessage(FaceDetectionRequest)

FaceDetectionResponse = _reflection.GeneratedProtocolMessageType('FaceDetectionResponse', (_message.Message,), {
  'DESCRIPTOR' : _FACEDETECTIONRESPONSE,
  '__module__' : 'model_service_pb2'
  # @@protoc_insertion_point(class_scope:FaceDetectionResponse)
  })
_sym_db.RegisterMessage(FaceDetectionResponse)

FaceRecognitionRequest = _reflection.GeneratedProtocolMessageType('FaceRecognitionRequest', (_message.Message,), {
  'DESCRIPTOR' : _FACERECOGNITIONREQUEST,
  '__module__' : 'model_service_pb2'
  # @@protoc_insertion_point(class_scope:FaceRecognitionRequest)
  })
_sym_db.RegisterMessage(FaceRecognitionRequest)

FaceRecognitionResponse = _reflection.GeneratedProtocolMessageType('FaceRecognitionResponse', (_message.Message,), {
  'DESCRIPTOR' : _FACERECOGNITIONRESPONSE,
  '__module__' : 'model_service_pb2'
  # @@protoc_insertion_point(class_scope:FaceRecognitionResponse)
  })
_sym_db.RegisterMessage(FaceRecognitionResponse)

SpeakerVerificationRequest = _reflection.GeneratedProtocolMessageType('SpeakerVerificationRequest', (_message.Message,), {
  'DESCRIPTOR' : _SPEAKERVERIFICATIONREQUEST,
  '__module__' : 'model_service_pb2'
  # @@protoc_insertion_point(class_scope:SpeakerVerificationRequest)
  })
_sym_db.RegisterMessage(SpeakerVerificationRequest)

SpeakerVerificationResponse = _reflection.GeneratedProtocolMessageType('SpeakerVerificationResponse', (_message.Message,), {
  'DESCRIPTOR' : _SPEAKERVERIFICATIONRESPONSE,
  '__module__' : 'model_service_pb2'
  # @@protoc_insertion_point(class_scope:SpeakerVerificationResponse)
  })
_sym_db.RegisterMessage(SpeakerVerificationResponse)

_MODELSERVICE = DESCRIPTOR.services_by_name['ModelService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\200\001\001'
  _REQUESTMETADATA._serialized_start=23
  _REQUESTMETADATA._serialized_end=60
  _RESPONSEMETADATA._serialized_start=62
  _RESPONSEMETADATA._serialized_end=121
  _FACEDETECTIONREQUEST._serialized_start=123
  _FACEDETECTIONREQUEST._serialized_end=197
  _FACEDETECTIONRESPONSE._serialized_start=199
  _FACEDETECTIONRESPONSE._serialized_end=279
  _FACERECOGNITIONREQUEST._serialized_start=281
  _FACERECOGNITIONREQUEST._serialized_end=376
  _FACERECOGNITIONRESPONSE._serialized_start=378
  _FACERECOGNITIONRESPONSE._serialized_end=451
  _SPEAKERVERIFICATIONREQUEST._serialized_start=453
  _SPEAKERVERIFICATIONREQUEST._serialized_end=533
  _SPEAKERVERIFICATIONRESPONSE._serialized_start=535
  _SPEAKERVERIFICATIONRESPONSE._serialized_end=612
  _MODELSERVICE._serialized_start=615
  _MODELSERVICE._serialized_end=869
# @@protoc_insertion_point(module_scope)
