from .ECAPA_TDNN import ECAPA_TDNN, ECAPA_TDNN_pool
from .model import ECAPA_TDNN1, ECAPA_TDNN2, ECAPA_TDNN_wav, ECAPA_TDNN_RNN, ECAPA_TDNN_flow, ECAPA_TDNN1_BN,\
    ECAPA_TDNN1_LN, ECAPA_TDNN1_CN, ECAPA_TDNN1_xs